version: '3'
services:
  backend:
    build: backend-endpoints/
    image: project/backend
    environment:
      - NODE_ENV=development
    ports: 
      - "3000:3000"
  ui:
    build: front/
    image: project/ui
    environment:
      - NODE_ENV=development
    ports: 
      - "8080:8080"